version: '3.8'

services:
  backend:
    build: ./backend
    env_file: .env.production
    environment:
      - NODE_ENV=production
    ports:
      - "80:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network

  db:
    image: postgres:15-alpine
    env_file: .env.production
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: prod_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user"]
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge