FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

COPY . .

EXPOSE 3000

RUN npx prisma migrate deploy

RUN npm run build

CMD ["npm", "start"]
